### PR TITLE
Pengww task no6

### PR DESCRIPTION
**Pull request by wangpw0103**
code for Geographic locations issue is ready for review and merge. Covered features include 
'Sites table in admin interface', ' adding new sites', 'editing sites' and 'deleting sites', refer to https://github.com/ecomontec/ecoSound-web/projects/10 for detail.

### CODE REVIEW

**Comment by kdarras** [comment]
Thanks. Several comments:
no need to show the user ID inside the admin interface:
image
However, the table should be filtered to only show the sites of the currently logged in admin.

Furthermore, the screenshot above shows that it is possible to input values that do not exist, for latitude and longitude. Please only allow values within this range for latitude: [-90,90] and for longitude: [-180,180]

Resize the columns to make the table fit

Typo in new site input mask: "centroid"

Make the input mask more compact: Latitude and longitude in one line, remove user line (it should not be possible to assign sites to someone else than oneself), GADM1,2,3 and centroid in one line.

Add info text for GADM1,2,3: Global Administrative Areas level 1,2,3

Handle input of wrong latitude and longitude values gracefully. Currently, they are excepted even though letters as input are clearly wrong, and the error message is not understandable:
image

**Comment by wangpw0103** [comment]
OK, I see. Code change based on comments is on-going.

**Comment by kdarras** [comment]
Changes successfully implemented. However, the collection view mode selection seems not to work anymore:
image

**Comment by kdarras** [comment]
thanks for fixing the collections table, but the fonts in the new site input mask are still inconsistent

**Comment by wangpw0103** [comment]
The screenshot is for your convenience
disable-boldfont
.

**Comment by wangpw0103** [comment]
The problem of ' when I select an item in the drop down list, it does not stay.' does not happen on my local run. Is this error stably reproduced in your environment?

**Comment by kdarras** [comment]
that problem does not occur anymore.
I fixed the input masks's inconsistent fonts, display the site ID in the recordings table, display the IDs in the recordings and users tables.
Please review and accept if all is good

**Comment by wangpw0103** [comment]
all changes are OK to me

**Pull request merged**
