### PR TITLE
task no7 milestone 1 along with minor changes of patch for task#6 sites

### PR DESCRIPTION
**Pull request by wangpw0103**
just for preview and check by Kevin. It should NOT be merged to master before code implementation of issues84 is included in next commits.

### CODE REVIEW

**Comment by kdarras** [comment]
Finally managed to test it.
It's nice to see that horizontal scrolling works on the sites table. Some more explanations for that: this feature should only be activated when the table becomes too wide (when the table is narrower than the vailable space, the bar should vanish). I understand that you probably made the sites table wider just to test that feature.
Vertical scrolling is not needed because we want to be able to use the pages browsing buttons (like below recordings table).

It's nice to have the very unobtrusive sorting of columns just by clicking on the table header, but it should work after the first click (I need to click twice to sort the table, after loading the recordings tab).

Nice to see the CC icons. Please hide the labels to see the icons only, otherwise it is a bit redundant. Also, open the CC page in new tab.

Please include a small demo sound test file inside the actual repository so that for each table, we have a corresponding entry - easier for testing and more consistent. I will send a file.

**Comment by kdarras** [comment]
looks good.

1. please use a blue color to differentiate the label from the sound name in the gallery view.
2. in the list view, please add the field name "My label" before the label. Also, this should be aligned horizontally with the Date field name and use consistent formatting.
3. different users still see the tag of other users but actually, users should only see their own. If you think we need to remove the automatic label filling with the default "not analysed", we can remove that.
4. Free text implementation is missing.
5. the site ID is still shown inside the recordings table but we need the site name.

**Comment by kdarras** [comment]
I will test [5d48369](https://github.com/ecomontec/ecoSound-web/pull/178/commits/5d48369f7346d9c0e5a529247f136dd54716b13a) as soon as I manage to install the local server. Fails so far for the usual reason.

**Comment by kdarras** [comment]
Unfortunately I cannot open the recordings tab in the admin interface:
image
so I cannot test the new labeling feature

**Comment by kdarras** [comment]
I checked the latest fix. I can access the recordings tab, and create new custom labels with free text.

remaining issues:

- please use a blue color to differentiate the label from the sound name in the gallery view.
- in the list view, please add the field name "My label" before the label. Also, this should be aligned horizontally with the Date field name and use consistent formatting.
- different users still see the tag of other users but actually, users should only see their own. If you think we need to remove the automatic label filling with the default "not analysed", we can remove that.
- the site ID is still shown inside the recordings table but we need the site name.

**Comment by wangpw0103** [comment]
> I checked the latest fix. I can access the recordings tab, and create new custom labels with free text.
> 
> remaining issues:
> 
> * please use a blue color to differentiate the label from the sound name in the gallery view.
> * in the list view, please add the field name "My label" before the label. Also, this should be aligned horizontally with the Date field name and use consistent formatting.
> * different users still see the tag of other users but actually, users should only see their own. If you think we need to remove the automatic label filling with the default "not analysed", we can remove that.
> * the site ID is still shown inside the recordings table but we need the site name.

The code changes cover all comments except 3rd one: different users still see the tag of other users but actually... 
1) Do you mean the labels here? 
2) Could you show more details of your test steps? 

Actually, I have paid attention to label data isolation between different users during development. And it works fine on my local env.

**Comment by kdarras** [comment]
I confirm that most changes have been made successfully.

Sorry, I meant the labels, not the tags, indeed (I edited the message above). Here is what I did:
- created one more collection
- uploaded 2 recordings to each collection
- created a normal user, gave him access to new collection
- logged in with user to assign labels and create a new, custom one
- logged in with admin to assign labels and create a new, custom one

Each user saw his own labels in the collection view and in the recording indeed. However, inside the drop-down list, the normal user saw admin's label ("admin_label")  and admin saw user label ("test_label"):
Screenshot from 2022-02-23 08-38-02
This drop-down menu should only display one's own labels.

Furthermore, the site field inside the recordings table should be editable.

**Comment by wangpw0103** [comment]
> I confirm that most changes have been made successfully.
> 
> Sorry, I meant the labels, not the tags, indeed (I edited the message above). Here is what I did:
> 
> * created one more collection
> * uploaded 2 recordings to each collection
> * created a normal user, gave him access to new collection
> * logged in with user to assign labels and create a new, custom one
> * logged in with admin to assign labels and create a new, custom one
> 
> Each user saw his own labels in the collection view and in the recording indeed. However, inside the drop-down list, the normal user saw admin's label ("admin_label") and admin saw user's label ("user_label"): Screenshot from 2022-02-23 08-38-02 This drop-down menu should only display one's own labels.
> 
> Furthermore, the site field inside the recordings table should be editable.

OK.  One thing to be clarified: the 'editable' site field in recordings table will be changed by selecting another site in drop-down list. And the drop-down list consists of site values created in site tab. Right?

**Comment by kdarras** [comment]
a) thanks for removing the top drop-down menu.
b) alright, then let's keep the site column non-sortable
c) regarding "all sites should always be displayed", I meant that the recordings table should not be filtered by site, so that all the (recordings') sites are always displayed (just like if you selected "all" in the former drop-down menu). It's ok like this now.
d) thanks for fixing the site selection

Remaining issues to complete task block 7:

- the mouse should not become a hand when hovering above the site column header in the recordings table, although it is not sortable
- other columns are not sortable yet or inconsistent: for example, date and name columns only sort in increasing order, cannot toggle to decreasing, and do not have a cursor that becomes a hand upon hovering above it. # and original filename columns need to be clicked twice to sort the entries. All columns need to be checked for all tables.
- resize the sites table to fit it to "standard" Full HD screens (currently with a side menu bar in Ubuntu, the table needs a horizontal scrollbar by only a small margin, whereas all other tables do not.)

a new bug: I cannot access the demo collection, so I could not check the label and CC icon features again.
image

**Comment by wangpw0103** [comment]
one more thing about tablesorter: 
even with this commit, an intermittent behavior is still there in present status. After several clickings, toggle-decreasing issue comes back. I wonder it's php specified issue since same code&function work well in plain html/js/css env. Actually, they work as well in Java/Spring sample. 
That's what I'm working on: look into the tablesorter framework, debug the problem in php env, and figure out the root cause, and then completely resolve it.

**Comment by kdarras** [comment]
OK thanks I ran it and confirm that the 3 first issues mentioned in the commit have been fixed.

**Comment by kdarras** [comment]
I tested it, and it ran more often.

However:

- after some clicking, the page can become blocked and crash:
image
- sometimes clicking a column header sorts it and then it quickly reverts back to the original order
- the columns that are sortable do not consistently have a hand when the cursor hovers above it (like "name", "date", "time" columns). All columns that are sortable should be visually recognisable with the hand cursor or, if you prefer (because some columns are not sortable), with a classical double arrow icon.

The requirement is not that the tables get sorted instantaneously: if it is not possible, we can leave it. However, the site must be stable for the user. If a spinning wheel or an hourglass must pop up to prevent further user input before the website becomes ready, we can do it (but I would like to avoid a page reload). Stability is more important than instant sorting.

**Comment by kdarras** [comment]
I think everything is implemented nicely now. The page selector task can be carried over to tasks block no8. Please comment on challenges and tried solutions in #55

**Pull request merged**
