### PR TITLE
collections management

### PR DESCRIPTION
**Pull request by wangpw0103**
the pr for collections management

### CODE REVIEW

**Comment by kdarras** [comment]
the edition, export, and creation of collection works well.

However, the following tasks remain:
"Rename Collection’s “citation” field to “DOI”. Remove “source” fields." (you can keep URL)

Also, the collection ID count seems discontinuous: new collections were added from id 42 onwards, although I had only one collection with id 1 from the start. It should start from 2, 3, etc.

Please order the collections by id.

**Comment by wangpw0103** [comment]
1) both remaining 'source' field and immutable 'DOI' filed are left in first commit of the PR to speed up the developing process. 2) the  discontinuous collection id is introduced from mauladi's database since it's merged in last PR. Both of them are known issues and will be fixed in next commit.

Now the '#' filed value comes from collection id, is it expected?

**Comment by kdarras** [comment]
Very well,
I am not sure why "#" is used for displaying IDs (maybe because it is shorter). The actual ID field name can be used instead (or an abreviated form) as we will have many tables in the admin interface.

**Comment by kdarras** [comment]
Excellent work!

Some issues remain:
In the admin interface, when adding a new collection, the collections table does not need to be hidden. It should stay visible.

The top drop-down "collections" menu should not display collections that the user does not have access to.
If a user is trying to access (maybe by typing URL) a collection that he/she does not have access to, please display a message such as "No access to collection" or the like.

In the permissions table in the admin interface, please rename "view" to "view all tags" and "review" to "review all tags" for clarity.

When changing permissions, an empty message appears. Please use something informative, such as "successfully changed user permissions"

**Comment by kdarras** [comment]
Additional issue: after stopping containers (docker-compose down) and restarting them (sh run.sh), I cannot test the localhost anymore:

`Fatal error: Uncaught PDOException: SQLSTATE[HY000] [2002] Connection refused in /var/www/html/src/BioSounds/Database/Database.php:37 Stack trace: #0 /var/www/html/src/BioSounds/Database/Database.php(37): PDO->__construct('mysql:host=data...', 'biosounds', 'biosounds', Array) #1 /var/www/html/src/BioSounds/Provider/BaseProvider.php(19): BioSounds\Database\Database->__construct('mysql', 'database', 'biosounds', 'biosounds', 'biosounds') #2 /var/www/html/src/BioSounds/Classes/BaseClass.php(83): BioSounds\Provider\BaseProvider->__construct() #3 /var/www/html/src/BioSounds/Classes/BaseClass.php(37): BioSounds\Classes\BaseClass->loadConfigFile() #4 /var/www/html/src/BioSounds/Controller/AppController.php(25): BioSounds\Classes\BaseClass->__construct() #5 /var/www/html/index.php(5): BioSounds\Controller\AppController->__construct() #6 {main} thrown in /var/www/html/src/BioSounds/Database/Database.php on line 37`

**Comment by wangpw0103** [comment]
> 
> 
> Excellent work!
> 
> Some issues remain: In the admin interface, when adding a new collection, the collections table does not need to be hidden. It should stay visible.
> 
> The top drop-down "collections" menu should not display collections that the user does not have access to. If a user is trying to access (maybe by typing URL) a collection that he/she does not have access to, please display a message such as "No access to collection" or the like.
> 
> In the permissions table in the admin interface, please rename "view" to "view all tags" and "review" to "review all tags" for clarity.
> 
> When changing permissions, an empty message appears. Please use something informative, such as "successfully changed user permissions"
> 
> order collections table by collection id

the issues mentioned are all fixed on commit by 4e4a531117395f3fa4bb21b014ee88eb5692bb7c. please check it

**Comment by wangpw0103** [comment]
> 
> 
> Additional issue: after stopping containers (docker-compose down) and restarting them (sh run.sh), I cannot test the localhost anymore:
> 
> `Fatal error: Uncaught PDOException: SQLSTATE[HY000] [2002] Connection refused in /var/www/html/src/BioSounds/Database/Database.php:37 Stack trace: #0 /var/www/html/src/BioSounds/Database/Database.php(37): PDO->__construct('mysql:host=data...', 'biosounds', 'biosounds', Array) #1 /var/www/html/src/BioSounds/Provider/BaseProvider.php(19): BioSounds\Database\Database->__construct('mysql', 'database', 'biosounds', 'biosounds', 'biosounds') #2 /var/www/html/src/BioSounds/Classes/BaseClass.php(83): BioSounds\Provider\BaseProvider->__construct() #3 /var/www/html/src/BioSounds/Classes/BaseClass.php(37): BioSounds\Classes\BaseClass->loadConfigFile() #4 /var/www/html/src/BioSounds/Controller/AppController.php(25): BioSounds\Classes\BaseClass->__construct() #5 /var/www/html/index.php(5): BioSounds\Controller\AppController->__construct() #6 {main} thrown in /var/www/html/src/BioSounds/Database/Database.php on line 37`

it's expected behavior because 'docker-compose down' will do two things: 1) stop the running containers, 2) remove containers, networks, volumes, and images created by 'docker-compose up'.
see the official document for detail https://docs.docker.com/compose/reference/down/

**Comment by kdarras** [comment]
I am checking the latest commit, but as usual, there are installation problems (`Package unzip is not available, but is referred to by another package. This may mean that the package is missing, has been obsoleted, or is only available from another source`)
I keep trying

**Comment by kdarras** [comment]
Very good!

2 minor remaining issues:

unchecking "Access" should uncheck the "view tags" and "review tags" checkboxes too (since they are hierarchical)

Please display the collection ID column (just like it is shown for recordings)

**Comment by wangpw0103** [comment]
> 
> 
> I see. I confused it with docker-compose stop
> 
> The last commit is very good
> 
> 2 minor remaining issues:
> 
>     * unchecking "Access" should uncheck the "view tags" and "review tags" checkboxes too (since they are hierarchical)
> 
>     * Please display the collection ID column (just like it is shown for recordings)

With commit 1f9ca560ff18e79cf3c4daf9a7861d5e7543c5f3, 'access' uncheck will trigger view&review and 'view' uncheck will trigger review as well.

**Comment by kdarras** [comment]
Tasks block 1 completed. Well done.

**Pull request merged**
