### PR TITLE
enable user password self service

### PR DESCRIPTION
**Pull request by wangpw0103**
Task of Set password self-service (https://github.com/ecomontec/ecoSound-web/issues/119) is ready for review. Any comments are appreciated. Thanks

### CODE REVIEW

**Comment by kdarras** [comment]
Excellent - it works!

Please name the dropdown link "administration" (just like for admins, for consistency) and integrate the user profile into a "users" tab (just like for admins, for consistency). The only difference would be that admins see all their users, and users see only their own user.
Excellent to show the permissions as read-only.

Nice to have: users should be able to set their own tag color (not just admins).

**Comment by kdarras** [comment]
I just noticed that when entering a password that does not meet the requirements, an unnecessary message pops up:
image

**Comment by wangpw0103** [comment]
Yeah, the 'hello' pop up is debug info. It must be removed in next commit. Thanks for reminding

**Comment by wangpw0103** [comment]
> Excellent - it works!
> 
> Please name the dropdown link "administration" (just like for admins, for consistency) and integrate the user profile into a "users" tab (just like for admins, for consistency). The only difference would be that admins see all their users, and users see only their own user. Excellent to show the permissions as read-only.
> 
> Nice to have - if you like: users should be able to set their own tag color (not just admins).

Do you mean the user's "Administration" page has only one tag: the "users" tag. And there are only two editable self-service fields: password and tag color. Is it right?

**Comment by kdarras** [comment]
I mean that it would be nice if users also saw a menu like this:
image
and once they are inside, the user table that you already show could be displayed next to a "user" (without "s") tab like the one admins see:
image

Yes, the only self-editable fields should be password and color.

This is because later, normal users will also need one more taB for their taGs :)

**Comment by kdarras** [comment]
excellent, Pengwei

**Review by kdarras — APPROVED** [review]

**Pull request merged**
