### PR TITLE
enable pagination for remaining admin tabs, including collections tab…

### PR DESCRIPTION
**Pull request by wangpw0103**
…, users tab and sites tab. The display pattern follows up recording tab

### CODE REVIEW

**Comment by kdarras** [comment]
Nice to see the page selector in most tabs, and that it is working in the recordings tab. However:

- sorting columns only works on the currently displayed page. However, it should sort the entire table
image
- Uploading mp3 recordings does not seem to work anymore, and I don't know when this stopped working
- the page selector does not collapse after 10 pages:
image

**Comment by wangpw0103** [comment]
> Nice to see the page selector in most tabs, and that it is working in the recordings tab. However:
> 
> * sorting columns only works on the currently displayed page. However, it should sort the entire table
>   image
Based on the brief description of the issue https://github.com/ecomontec/ecoSound-web/issues/55 and the perspective of web dev, the 'sortable' should work on page but not for whole entire table. Actually, if it's entire table sortable, it's not enough to only take a front-end library.
> * Uploading mp3 recordings does not seem to work anymore, and I don't know when this stopped working
I have tried on both admin user and another user against differenct collections. They work well on my machine. Do you try it on clean env? The 'clean' means: clean docker container, clean docker volume and clean docker images.
> * the page selector does not collapse after 10 pages:
>   image
Yeah, the feature of selector collapse is not implemented. Sorry for forgetting including this information on commit comments.

**Comment by kdarras** [comment]
I see. In that case, the column sorting feature should be removed. It's a bit disappointing because only sorting on the entire table is useful, not page-level sorting.
I will try MP3 upload with the next commit again. Looking forward to the page selector collapse feature

**Comment by wangpw0103** [comment]
The page selector collapsing is ready for review on commit 7b612c6.

**Comment by wangpw0103** [comment]
The function implementation of the code is based on requirement of https://github.com/ecomontec/ecoSound-web/issues/118, and the design detail comes from https://developers.google.com/search/docs/advanced/ecommerce/pagination-and-incremental-page-loading#sequentially.

**Comment by kdarras** [comment]
The page selector functions well and is neat, thanks! Happy to merge if it has been implemented everywhere.

**Review by kdarras — APPROVED** [review]

**Pull request merged**
