### PR TITLE
sync-up task no4

### PR DESCRIPTION
**Pull request by wangpw0103**
code base align with task#4, the change detail can be referred in https://docs.google.com/document/d/1n85_9YW8C3g9l0w8-lLgcxutFCzcEicy2uX7mG4iwbA

### CODE REVIEW

**Comment by kdarras** [comment]
This is the re-design task (reorganising menu, integrating global soundscapes project, black background and new ecosound-web logos)

**Review by kdarras — DISMISSED** [review]

**Comment by kdarras** [comment]
The redesign was mostly successful, however, the small ecosound-web logo is not displayed inside the browser, and the collections entries are not accessible (leading to "collection not found" message). It needs to be clear what data will be used inside the docker installation and what data need to be used in the production server.
I suggest that only demo collections (demo open collection, demo reference collection, demo normal collection) are available in the local app, but if you think it is not crucial or bothersome, we can wait until proper implementation of projects and open collections is completed.

**Comment by kdarras** [comment]
I re-updated the local environment and re-ran it, and still, the old biosounds logo is shown in the tab icon in FF and Chrome.

**Comment by wangpw0103** [comment]
> I re-updated the local environment and re-ran it, and still, the old biosounds logo is shown in the tab icon in FF and Chrome. PS: I mean the small icon inside the browser tab. Not the small icon inside the top menu of the web page. image

We need a new icon file to display on the tab. The old biosounds icon file name is biosounds_favicon.png, and the resolution is 16 pixels (width) X 13 pixels (height). The detail can be referred when creating new icon.

**Comment by wangpw0103** [comment]
I have tried the current small logo as icon on test server.  It looks a little weird because almost all icon files are transparency but our logo files are white on black! You will create new transparency icon image, right? 
ecos-web-icon

**Comment by kdarras** [comment]
Yes, All these files were created. You were probably looking either for "ecosound-web logo_small_black_on_alpha.svg" or "ecosound-web logo_small_white_on_alpha.svg"
"Alpha" is the channel that handles transparency.

**Comment by wangpw0103** [comment]
It doesn't seem work either when using the ecosound-web logo_small_black_on_alpha.svg as icon. The icon file is already updated in test server. It can be checked right now.

**Comment by kdarras** [comment]
I used the SVG to generate a small PNG with black symbol on alpha (transparent) channel. It works for me in FF and Chrome on biosounds_test. Please check.
Don't forget to update all logo file names to reflect the new server name and the type of design (maybe just use my file names).

**Comment by wangpw0103** [comment]
> I used the SVG to generate a small PNG with black symbol on alpha (transparent) channel. It works for me in FF and Chrome on biosounds_test. Please check. Please update the production server too. and don't forget to update all logo file names to reflect the new server name and the type of design (maybe just use my file names).
> 
> Maybe you used a program that does not handle transparency well to generate your PNG.

Cool! I see the icon of test server. It works well and is expected. I have copy the icon to product server. The next commit of the PR will include the icon as well. 

Actually, I do not have any image software. The icon file I tried was generated through the export feature of 'Internet Explorer'.

**Comment by kdarras** [comment]
Oh right, I try to avoid IE as much as possible. You could try Inkscape, it is an excellent, free, open-source, professional graphics software.

**Comment by wangpw0103** [comment]
The PR is ready for review & merged since local run passed.

**Review by kdarras — APPROVED** [review]

**Comment by wangpw0103** [comment]
> Oh right, I try to avoid IE as much as possible. You could try Inkscape, it is an excellent, free, open-source, professional graphics software. By the way, could you try to see whether ecoSound-web can be accessed/rendered without problems with the most common Chinese browser? (I don't know which one that is, but recently, in a lab meeting, a colleague tried QQ browser and it did not load)

Looks like ecoSound-web rendering issue is 'Internet Explore' based problem but not Chinese browser :) The pages can't even be loaded/rendered in built-in IE browser on my laptop. As I know, the IE engine based browser on China market is not as popular as before, but some large companies product still run on it, including QQ, sogou and baidu. 
Not sure if it's hard requirement for ecoSound-web to keep compatible with IE engine, but in my mind, it's another story and should be difficult to perform front-end tuning for IE compatibility.
It's up to you :)

**Comment by kdarras** [comment]
OK no need as long as it is working on Chrome, Firefox and Safari

**Pull request merged**
